database:
  host: 127.0.0.1
  port: 5433
  name: byrdi
  user: postgres
  password: Swoop123!
  connection_string: postgresql://postgres:Swoop123!@127.0.0.1:5433/byrdi
  schema:
    - items
    - categories
    - menus
    - locations
    - orders
    - order_items
    - users
    - markers
    - order_ratings

services:
  sql_generator:
    model: gpt-4o
    temperature: 0.1
    max_tokens: 2000
    examples_path: /c:/Python/GIT/swoop-ai/services/sql_generator/sql_files/
  rules:
    rules_path: /c:/Python/GIT/swoop-ai/services/rules
    resources_dir: /c:/Python/GIT/swoop-ai/ai_testing_agent/resources
    sql_files_path: /c:/Python/GIT/swoop-ai/services/sql_generator/sql_files
    cache_ttl: 3600
    
testing:
  provide_fallback_responses: true
  generate_critiques: true
  sql_schema_validation: true
  detect_empty_sql: true 