database:
  host: ${DB_HOST:-127.0.0.1}
  port: ${DB_PORT:-5433}
  name: ${DB_NAME:-byrdi}
  user: ${DB_USER:-postgres}
  password: ${DB_PASSWORD:-Swoop123!}
  connection_string: ${DB_CONNECTION_STRING:-postgresql://postgres:Swoop123!@127.0.0.1:5433/byrdi}
  schema:
    - items
    - categories
    - menus
    - locations
    - orders
    - order_items
    - users
    - markers
    - order_ratings

services:
  sql_generator:
    model: gpt-4o
    temperature: 0.1
    max_tokens: 2000
    examples_path: /c:/Python/GIT/swoop-ai/services/sql_generator/sql_files/
    openai_api_key: ${OPENAI_API_KEY}
  rules:
    rules_path: /c:/Python/GIT/swoop-ai/services/rules
    resources_dir: /c:/Python/GIT/swoop-ai/resources
    sql_files_path: /c:/Python/GIT/swoop-ai/services/sql_generator/sql_files
    cache_ttl: 3600
    
testing:
  provide_fallback_responses: true
  generate_critiques: true
  sql_schema_validation: true
  detect_empty_sql: true
  use_real_services: ${ENABLE_REAL_SERVICES:-false}
  debug_mode: ${DEBUG_MODE:-true} 